module.exports = {
  'import/no-unresolved': [
    'error',
    {
      commonjs: true,
      amd: false,
      caseSensitive: true,
    },
  ],
  'import/named': 'error',
  'import/default': 'error',
  'import/namespace': 'error',
  'import/no-restricted-paths': 'off',
  'import/no-absolute-path': 'error',
  'import/no-dynamic-require': 'off',
  'import/no-internal-modules': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/no-self-import': 'error',
  'import/no-cycle': ['error', { maxDepth: Infinity }],
  'import/no-useless-path-segments': 'error',
  'import/export': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-deprecated': 'off',
  'import/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: [
        'test/**',
        'tests/**',
        'spec/**',
        '**/__tests__/**',
        '**/__mocks__/**',
        'test.{js,jsx}',
        'test-*.{js,jsx}',
        '**/*{.,_}{test,spec}.{js,jsx}',
        '**/jest.config.js',
        '**/webpack.config.js',
        '**/webpack.config.*.js',
        '**/rollup.config.js',
        '**/rollup.config.*.js',
        '**/gulpfile.js',
        '**/gulpfile.*.js',
        '**/Gruntfile{,.js}',
        '**/protractor.conf.js',
        '**/protractor.conf.*.js',
      ],
      optionalDependencies: false,
      peerDependencies: false,
    },
  ],
  'import/no-mutable-exports': 'error',
  'import/unambiguous': 'off',
  'import/no-commonjs': 'off',
  'import/no-amd': 'error',
  'import/no-nodejs-modules': 'off',
  'import/first': ['error', 'absolute-first'],
  'import/exports-last': 'off',
  'import/no-duplicates': 'error',
  'import/no-namespace': 'off',
  'import/extensions': [
    'error',
    'always',
    {
      js: 'never',
      mjs: 'never',
      jsx: 'never',
    },
  ],
  'import/order': [
    'off',
    {
      groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
      'newlines-between': 'never',
    },
  ],
  'import/newline-after-import': 'error',
  'import/prefer-default-export': 'off',
  'import/max-dependencies': 'off',
  'import/no-unassigned-import': 'off',
  'import/no-named-default': 'error',
  'import/no-default-export': 'off',
  'import/no-anonymous-default-export': [
    'off',
    {
      allowArray: true,
      allowArrowFunction: false,
      allowAnonymousClass: false,
      allowAnonymousFunction: false,
      allowCallExpression: true,
      allowLiteral: true,
      allowObject: true,
    },
  ],
  'import/group-exports': 'off',
};
