module.exports = {
  'import/no-unresolved': [
    'error',
    {
      commonjs: true,
      amd: false,
      caseSensitive: true,
    },
  ],
  'import/named': 'error',
  'import/default': 'error',
  'import/namespace': 'error',
  'import/no-restricted-paths': 'off',
  'import/no-absolute-path': 'error',
  'import/no-dynamic-require': 'off',
  'import/no-internal-modules': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/no-self-import': 'error',
  'import/export': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-deprecated': 'off',
  'import/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: false,
      optionalDependencies: false,
      peerDependencies: false,
    },
  ],
  'import/no-mutable-exports': 'error',
  'import/unambiguous': 'off',
  'import/no-commonjs': 'off',
  'import/no-amd': 'error',
  'import/no-nodejs-modules': 'off',
  'import/first': 'off',
  'import/exports-last': 'error',
  'import/no-duplicates': 'error',
  'import/no-namespace': 'off',
  'import/extensions': [
    'error',
    'always',
    {
      js: 'never',
      mjs: 'never',
      jsx: 'never',
    },
  ],
  'import/order': [
    'off',
    {
      groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
      'newlines-between': 'never',
    },
  ],
  'import/newline-after-import': 'error',
  'import/prefer-default-export': 'off',
  'import/max-dependencies': 'off',
  'import/no-unassigned-import': 'off',
  'import/no-named-default': 'error',
  'import/no-default-export': 'off',
  'import/no-anonymous-default-export': [
    'error',
    {
      allowArray: true,
      allowArrowFunction: false,
      allowAnonymousClass: false,
      allowAnonymousFunction: false,
      allowCallExpression: true,
      allowLiteral: true,
      allowObject: true,
    },
  ],
  'import/group-exports': 'off',
};
