module.exports = {
  'for-direction': 'error',
  'getter-return': ['error', { allowImplicit: true }],
  'no-await-in-loop': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': ['warn', { allow: ['warn', 'error'] }],
  'no-constant-condition': ['warn', { checkLoops: true }],
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-dupe-args': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-empty-character-class': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-func-assign': 'error',
  'no-inner-declarations': ['error', 'functions'],
  'no-invalid-regexp': ['error', { allowConstructorFlags: [] }],
  'no-irregular-whitespace': [
    'error',
    {
      skipStrings: true,
      skipComments: false,
      skipRegExps: false,
      skipTemplates: true,
    },
  ],
  'no-obj-calls': 'error',
  'no-prototype-builtins': 'error',
  'no-regex-spaces': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'use-isnan': 'error',
  'valid-jsdoc': 'off',
  'valid-typeof': ['error', { requireStringLiterals: true }],
};
